---
title: "Identifying predictors of postoperative blood-related health complications"
author: "Ryan Shi"
output: 
    html_document
---

# Description

Health complications following surgery, or postoperative health complications, pose problems to treatment efficacy and often contribute to higher healthcare costs (Dencker et al. 2021). Potential factors for these complications include hospital-acquired infections or healthcare-associated infections (HAI), which are common in hospitals and can increase morbidity and mortality in patients (Kanerva et al. 2008). Other factors that may influence the treatment of patients include staff vaccination rates (Hollmeyer et al. 2012) and emergency department (ED) volume (Brar et al. 2013).

In this project, I aim to identify reliable predictors of postoperative blood-related health complications, using public datasets on [CMS.gov](https://www.cms.gov/) collected from 5424 hospitals registered with Medicare in the United States. For each hospital, these datasets record data on HAI, the timeliness and efficacy of care, and complications and death. I start with data wrangling, EDA, and regression analysis. Then, I fit models with bagging, random forests, and XGBoost and evaluate metrics on performance and variable importance.

To access the project, refer to the following:

- [Project repository](https://github.com/ryancys1234/JSC370-Project)

- [Data used](https://github.com/ryancys1234/JSC370-Project/tree/main/data)

- [PDF report](https://raw.githubusercontent.com/ryancys1234/JSC370-Project/main/Final.pdf)

- [Video demonstration](https://play.library.utoronto.ca/watch/ff007b2e46c76d6a177b4f017901ae8b)
